apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: uluru
spec:
  version: 7.8.1
  count: 1
  elasticsearchRef:
    name: uluru
  podTemplate:
    spec:
      nodeSelector:
        workload: apps
