kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: balanced
provisioner: pd.csi.storage.gke.io
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
parameters:
  type: pd-balanced
